spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentms?setUnicode=true&characterEncoding=utf8&useAffectedRows=true&useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.ytl.student_server.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8888